/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type PackageScope = 'Cluster' | 'Namespaced';

export interface HttpsGlasskubeDevSchemasV1IndexJson {
  packages: PackageRepoIndexItem[];
}
export interface PackageRepoIndexItem {
  name: string;
  shortDescription?: string;
  iconUrl?: string;
  latestVersion?: string;
  scope?: PackageScope;
}
