/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface HttpsGlasskubeDevSchemasV1PackageManifestJson {
  name: string;
  shortDescription?: string;
  longDescription?: string;
  references?: PackageReference[];
  iconUrl?: string;
  helm?: HelmManifest;
  kustomize?: KustomizeManifest;
  manifests?: PlainManifest[];
  defaultNamespace: string;
  entrypoints?: PackageEntrypoint[];
}
export interface PackageReference {
  label: string;
  url: string;
}
export interface HelmManifest {
  repositoryUrl: string;
  chartName: string;
  chartVersion: string;
  values?: JSON;
}
export interface JSON {
  [k: string]: unknown;
}
export interface KustomizeManifest {}
export interface PlainManifest {
  url: string;
}
export interface PackageEntrypoint {
  name?: string;
  serviceName: string;
  port: number;
  localPort?: number;
  scheme?: string;
}
