name: Setup @glasskube/scout
description: Install @glasskube/scout globally using npm
inputs:
  token:
    required: true
    description: GitHub Token for NPM registry
outputs: {}
runs:
  using: "composite"
  steps:
    - name: Setup node.js
      uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4
      with:
        node-version: "20"
        registry-url: "https://npm.pkg.github.com"
        scope: "@glasskube"
    - name: Install scout
      shell: sh
      run: npm install --global @glasskube/scout@0.3.4 # x-release-please-version
      env:
        NODE_AUTH_TOKEN: ${{ inputs.token }}
