name: Test actions/setup

on:
  push:
    paths:
      - actions/**

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      packages: read
    steps:
      - name: Checkout
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4
      - name: Setup scout
        uses: ./actions/setup
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: scout --version
