name: Test actions/setup

on:
  push:
    paths:
      - actions/**

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      packages: read
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Setup scout
        uses: ./actions/setup
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: scout --version
