name: Test actions/setup

on:
  push:
    paths:
      - actions/**

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      packages: read
    steps:
      - name: Checkout
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4
      - name: Setup scout
        uses: ./actions/setup
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: scout --version
