name: Update Changelog & Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  release-please:
    permissions:
      contents: write # for google-github-actions/release-please-action to create release commit
      pull-requests: write # for google-github-actions/release-please-action to create release PR
    runs-on: ubuntu-latest
    outputs:
      releases_created: ${{ steps.release-please.outputs.releases_created }}
      tag_name: ${{ steps.release-please.outputs.tag_name }}
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Release Please
        id: release-please
        uses: google-github-actions/release-please-action@e4dc86ba9405554aeba3c6bb2d169500e7d3b4ee # v4.1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  publish:
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    needs:
      - release-please
    if: ${{ needs.release-please.outputs.releases_created == 'true' }}
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 0
      - name: Setup node.js
        uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # v4
        with:
          node-version: '20'
          cache: npm
          registry-url: 'https://npm.pkg.github.com'
          scope: '@glasskube'
      - name: Install dependencies
        run: npm ci
      - name: Build application
        run: npm run build
      - name: Publish to GitHub Packages
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
